site_name: 52-09 Operations Manual
site_description: Living documentation for systems, procedures, safety, and maintenance
site_url: https://barretcunningham.github.io/5209
repo_url: https://github.com/barretcunningham/5209
repo_name: barretcunningham/5209

theme:
  name: material
  logo: assets/img/neel-logo.svg
  favicon: assets/img/neel-logo.svg
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Jost
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

plugins:
  - search
  - tags

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Introduction:
    - Overview: introduction/index.md
    - Boat Overview: introduction/overview.md
    - Particulars: introduction/particulars.md
  - Power:
    - Overview: power/index.md
    - 12V System: power/electrical-12v.md
    - AC System: power/electrical-ac.md
    - Equipment:
      - Safiery Meteor 48V: power/equipment/safiery-meteor-48v.md
      - Scotty V3 24-48 DC/DC: power/equipment/scotty-v3-24-48-dcdc.md
      - Victron 12/165 Gel 24V: power/equipment/victron-12-165-gel-24v.md
  - Water:
    - Overview: water/index.md
    - Water Systems: water/systems.md
  - Waste:
    - Overview: waste/index.md
    - Waste Systems: waste/systems.md
  - Sails and Rigging:
    - Overview: sails-and-rigging/index.md
    - Reefing: sails-and-rigging/reefing.md
  - Navigation:
    - Overview: navigation/index.md
    - Navigation Systems: navigation/systems.md
    - Communications: navigation/communications.md
    - Heavy Weather: navigation/heavy-weather.md
  - Propulsion:
    - Overview: propulsion/index.md
    - Propulsion Systems: propulsion/systems.md
  - Appliances:
    - Overview: appliances/index.md
  - Anchoring and Mooring:
    - Overview: anchoring-and-mooring/index.md
    - Anchoring: anchoring-and-mooring/anchoring.md
    - Arrival: anchoring-and-mooring/arrival.md
    - Departure: anchoring-and-mooring/departure.md
  - Emergency:
    - Overview: emergency/index.md
    - Emergency Procedures: emergency/overview.md
    - Checklists:
      - Overview: emergency/checklists/index.md
      - Man Overboard: emergency/checklists/mob.md
      - Fire: emergency/checklists/fire.md
      - Flooding: emergency/checklists/flooding.md
      - Abandon Ship: emergency/checklists/abandon-ship.md
    - Equipment: emergency/equipment/index.md
  - Maintenance:
    - Overview: maintenance/overview.md

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/barretcunningham/5209
