title: "NEEL 52 – Boat Operations Manual"
description: "Living documentation for systems, procedures, safety, and maintenance."

# Use the Chirpy theme via remote_theme (works on GitHub Pages)
remote_theme: cotes2020/jekyll-theme-chirpy

# Chirpy requires include-cache for performance on GitHub Pages
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Basic options
# Theme options (Chirpy)
theme_mode: light    # options: light, dark, auto
logo:                # path to logo if used (e.g., /assets/img/logo.png)
avatar: /assets/img/logo.jpg

# URL structure
permalink: pretty

# Navigation order via page front matter `nav_order`
# Navigation note: Chirpy uses pages, posts, and optional tabs.
# We will keep existing pages; sidebar/nav will follow Chirpy defaults.

# Build settings (keep minimal for GitHub Pages)
markdown: kramdown
exclude:
  - "scripts"
  - "vendor"

# Optional: add useful links in the header (fill in repo later if desired)
# aux_links:
#   "View on GitHub": "https://github.com/OWNER/REPO"
