title: "NEEL 52 – Boat Operations Manual"
description: "Living documentation for systems, procedures, safety, and maintenance."

# Use the Chirpy theme (Jekyll 4.x via GitHub Actions)
theme: jekyll-theme-chirpy

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Basic options
# Theme options (Chirpy)
theme_mode: light    # options: light, dark, auto
logo:                # path to logo if used (e.g., /assets/img/logo.png)
avatar: /assets/img/logo.jpg

# URL structure
permalink: pretty
url: https://barretcunningham.github.io
baseurl: /5209

# Navigation order via page front matter `nav_order`
# Navigation note: Chirpy uses pages, posts, and optional tabs.
# We will keep existing pages; sidebar/nav will follow Chirpy defaults.

# Build settings (keep minimal for GitHub Pages)
markdown: kramdown
lang: en
timezone: Etc/UTC
exclude:
  - "scripts"
  - "vendor"

# Optional: add useful links in the header (fill in repo later if desired)
# aux_links:
#   "View on GitHub": "https://github.com/OWNER/REPO"
